persistence:
  storageClass: local-path

controller:
  ingress:
    enabled: true
    apiVersion: networking.k8s.io/v1
    annotations:
      cert-manager.io/cluster-issuer: "ingress-cert-issuer"
    ingressClassName: nginx
    hostName: jenkins.localhost
    tls:
      - secretName: jenkins-tls
        hosts:
          - jenkins.localhost
