installCRDs: true

extraObjects:
  - |-
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: ingress-cert-issuer
    spec:
      ca:
        secretName: own-ca

image:
  repository: registry:5001/quay.io/jetstack/cert-manager-controller
webhook:
  image:
    repository: registry:5001/quay.io/jetstack/cert-manager-webhook
cainjector:
  image:
    repository: registry:5001/quay.io/jetstack/cert-manager-cainjector
