---
fullnameOverride: vault

server:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: ingress-cert-issuer
    ingressClassName: nginx
    hosts:
      - host: vault.localhost
        path: []
    tls:
      - secretName: vault-tls
        hosts:
          - vault.localhost
  dataStorage:
    enabled: true
    storageClass: local-path
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain

  image:
    repository: registry:5001/docker.io/hashicorp/vault

injector:
  image:
    repository: registry:5001/docker.io/hashicorp/vault-k8s
  agentImage:
    repository: registry:5001/docker.io/hashicorp/vault
