global:
  domain: argocd.localhost
  image:
    repository: registry:5001/quay.io/argoproj/argocd

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "ingress-cert-issuer"
    tls: true

configs:
  cm:
    create: true

    resource.customizations: |
      admissionregistration.k8s.io/MutatingWebhookConfiguration:
        ignoreDifferences: |
          jsonPointers:
          - /webhooks/0/clientConfig/caBundle

    # See https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#argocd-app
    resource.customizations.health.argoproj.io_Application: |
      hs = {}
      hs.status = "Progressing"
      hs.message = ""
      if obj.status ~= nil then
        if obj.status.health ~= nil then
          hs.status = obj.status.health.status
          if obj.status.health.message ~= nil then
            hs.message = obj.status.health.message
          end
        end
      end
      return hs

  params:
    server.insecure: true

redis:
  image:
    repository: registry:5001/public.ecr.aws/docker/library/redis
