global:
  domain: argocd.localhost
  image:
    repository: registry:5001/quay.io/argoproj/argocd

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "ingress-cert-issuer"
    tls: true

configs:
  cm:
    create: true

    resource.customizations: |
      admissionregistration.k8s.io/MutatingWebhookConfiguration:
        ignoreDifferences: |
          jsonPointers:
          - /webhooks/0/clientConfig/caBundle

  params:
    server.insecure: true

redis:
  image:
    repository: registry:5001/public.ecr.aws/docker/library/redis
