outputs_dir: "{{ playbook_dir }}/../outputs"

virtual_machine:
  name: kubernetes
  cpus: 2
  memory: 4G
  disk: 20G

crio_version: "1.30"
kubernetes_version: "1.30"
kubernetes_cluster_name: "kubernetes"
kubernetes_service_cidr: "172.16.0.0/18"
kubernetes_pod_cidr: "10.85.0.0/16" # CRIO's default (hardcoded); TODO: implement
