controller:
  config:
    entries:
      external-status-address: "127.0.0.1"
  service:
    type: NodePort
    httpPort:
      nodePort: 30080
    httpsPort:
      nodePort: 30443

  extraArgs:
    report-ingress-status:
