---
controller:
  config:
    entries:
      external-status-address: "127.0.0.1"
      set-real-ip-from: "127.0.0.1"
      real-ip-header: "X-Forwarded-For"
      client-max-body-size: "0"

  service:
    type: NodePort
    httpPort:
      nodePort: 30080
    httpsPort:
      nodePort: 30443

  extraArgs:
    report-ingress-status:

  image:
    repository: registry:5001/docker.io/nginx/nginx-ingress
